[app]
name = "Space, man"
category = "Apps"

[entry]
class = "SpaceManApp"

[metadata]
author = "Nic"
license = "MIT"
url = "https://github.com/N1c0/tildagon-Spaceman/"
description = "App for EMF 26: Scroll the planets, the Sun, the Moon and a rocket. Auto-advances, shake to pick random object. Manually control with E & B buttons. Can display QR codes for Nibula Pen Plotter. Select object with C"
version = "3"
