[app]
name = "Space, man"
category = "Apps"

[entry]
class = "SpaceManApp"

[metadata]
author = "Nic"
license = "MIT"
url = "https://github.com/your-username/space-man"
description = "For the 26 theme: Scroll the planets, the Sun, the Moon and a rocket. Auto-advances, shake to restart. Manually control with E & B buttons"
version = "1"
